name: Push (develop)

on:
  push:
    branches: ["develop"]

jobs:
  drawio:
    runs-on: ubuntu-latest # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Convert .drawio file to image
        uses: Burnett01/actions-drawio@1.2
        with:
          src: ProjectStructure.drawio
          dest: ProjectStructure.png

      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-structure
          path: ProjectStructure.png
          if-no-files-found: error
